# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Devdanlevy
email: devdanlevy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is meant to introduce Devdanlevy.  It will include links to resume,
  github, twitter, and a blog detailing the process of breaking into the tech industry
  as a second career.  It will also include musings on life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://devdanlevy.com" # the base hostname & protocol for your site
twitter_username: devdanlevy1
github_username:  devdanlevy2
linkedin_username: daniel-levy-4758a7115
# Build settings
markdown: kramdown
